DROP DATABASE IF EXISTS visitservice;
DROP USER IF EXISTS `visit_service`@`%`;
CREATE DATABASE IF NOT EXISTS visitservice CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `visit_service`@`%` IDENTIFIED WITH mysql_native_password BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `visitservice`.* TO `visit_service`@`%`;
FLUSH PRIVILEGES;

